### ISSUE TITLE
Program Errors On Proces

### ISSUE THREAD

**Issue by peterfeddo** [psal/anonymouth#1]
Every time I click the process button I get a popup "Something went very wrong error". Then the program proceeds to crash after pressing okay.
![image](https://f.cloud.github.com/assets/528864/917675/546c424e-fea8-11e2-8a16-58793d570ef2.png)

**Comment by barrowclift** [comment]
Hello Peter,

Thanks for your interest in the Anonymouth Project! 

It seems you are using one of the older Anonymouth builds (it looks like the one from the direct download on our wiki, which we are in the process of updating, it's over a year old I believe). If you want to use a recent build, for now you'll have to clone the repo and build yourself using Eclipse or Terminal. If you have any more questions/errors messages/strange bugs, please don't hesitate to let us know, we truly appreciate feedback. Thanks again!

-Marc

**Comment by GitUser73937** [comment]
Can this error be marked as Closed?

**Comment by peterfeddo** [comment]
I don’t know. I gave up on trying the project as I wasn’t able to get it working with the sources provided at the time.
